### ISSUE TITLE
After initial connection and disconnection, proxy goes into loop

### ISSUE THREAD

**Issue by kormoc** [dccmx/tcproxy#1]
strace shows

```
epoll_wait(4, {{EPOLLIN, {u32=16, u64=16}}, {EPOLLIN, {u32=10, u64=10}}, {EPOLLIN, {u32=14, u64=14}}, {EPOLLIN, {u32=8, u64=8}}}, 1024, 4294967295) = 4
recvfrom(16, "", 2089224, 0, NULL, NULL) = 0
recvfrom(10, "", 2070591, 0, NULL, NULL) = 0
recvfrom(14, "", 2067917, 0, NULL, NULL) = 0
recvfrom(8, "", 2079748, 0, NULL, NULL) = 0
```

The recvfrom increments after each connection is closed and grows ever larger

**Comment by dccmx** [comment]
I don't quite understand what increments means, but I do fix a bug when remote peer is closed and proxy goes into infinite loop bug. Maybe that is the same problem you found. Tell me if not:-)

**Comment by kormoc** [comment]
That sounds like it could fix it.

the recvfrom line gets duplicated every time a new connection closes.

**Comment by kormoc** [comment]
That did the trick. Thanks!
